{
    "seed": 2,
    "foot_pcs": [2, 2, 2, 1],
    "chords": ["MAJOR_TRIAD", "MINOR_TRIAD", "MAJOR_63", "MAJOR_TRIAD"],
    "scales": ["LYDIAN", "DORIAN", "LOCRIAN", "MAJOR_SCALE"],
    "force_foot_in_bass": "global_first_note",
    "onset_density": 0.5,
    "dur_density": 0.5,
    "min_dur": 0.25,
    "voice_ranges": "AUTHENTIC_OCTAVES * C * OCTAVE3",
    "voice_lead_chord_tones": True,
    "num_voices": 3,
    "max_repeated_notes": -1,
    "allow_voice_crossings": False,
    "forbidden_intervals": [0],
    "output_path": "EFFRHY/docs/examples/midi/",
    "overwrite": True,
    # overriding web defaults
    "randomly_distribute_between_choirs": False,
    "tempo": 120,
    "max_consec_seg_from_same_choir": 0,
    "length_choir_segments": 1,
    "preserve_foot_in_bass": "none",
}
