{
    "seed": 2,
    "pattern_len": 4,
    "consonance_treatment": "none",
    "harmony_len": 4,
    "output_path": "EFFRHY/docs/examples/midi/",
    "overwrite": True,
    "force_foot_in_bass": "first_beat",
    "extend_bass_range_for_foots": 7,
    "voice_lead_chord_tones": True,
    "attack_density": 0.7,
    "dur_density": 0.7,
    "unison_weighted_as": "SECOND",
    "randomly_distribute_between_choirs": True,
    "length_choir_segments": 1 / 4,
    "tempo": 132,
    "choirs_separate_tracks": False,
}
