{
    "seed": 368,
    "num_voices": 2,
    "pattern_len": 5.5,
    "rhythm_len": 8,
    "pitch_loop": False,
    "harmony_len": 4,
    "truncate_patterns": True,
    "voice_order_str": "usual",
    "interval_cycle": (7, 2, 2, 7),
    "chords": (
        (1.33333, 1.66667, 2),
        (1.66667, 2, 2.5),
        (1.25, 1.5, 1.875),
        (1.0, 1.25, 1.5),
    ),
    "parallel_voice_leading": False,
    "voice_lead_chord_tones": False,
    "preserve_foot_in_bass": "none",
    "chord_tone_and_foot_disable": False,
    "chord_tone_selection": True,
    "force_chord_tone": "first_beat",
    "chord_tones_sync_onset_in_all_voices": True,
    "force_foot_in_bass": "first_note",
    "prefer_small_melodic_intervals": False,
    "force_repeated_notes": True,
    "force_parallel_motion": False,
    "consonance_treatment": "all_durs",
    "cont_rhythms": "none",
    "vary_rhythm_consistently": False,
    "rhythmic_unison": False,
    "rhythmic_quasi_unison": False,
    "hocketing": False,
    "onset_density": (1, 0.8),
    "dur_density": 0.9,
    "onset_subdivision": 0.25,
    "randomly_distribute_between_choirs": True,
    "length_choir_segments": 0.25,
    "tempo": 113,
}
