{
    "seed": 2453683881,
    "num_voices": 3,
    "pattern_len": (4.5, 2.5, 7.5),
    "rhythm_len": (3, 3, 6.5),
    "pitch_loop": False,
    "harmony_len": (4.5, 2.5, 7.5),
    "truncate_patterns": True,
    "voice_order_str": "usual",
    "interval_cycle": (10, 11, 4, 11, 0, 1),
    "chords": ((1.33333, 1.66667, 2), (1.5, 1.875, 2.25), (1.5, 1.875, 2.25)),
    "parallel_voice_leading": False,
    "voice_lead_chord_tones": True,
    "preserve_foot_in_bass": "all",
    "chord_tone_and_foot_disable": False,
    "chord_tone_selection": True,
    "force_chord_tone": "none",
    "chord_tones_sync_onset_in_all_voices": False,
    "force_foot_in_bass": "global_first_note",
    "prefer_small_melodic_intervals": False,
    "force_repeated_notes": True,
    "force_parallel_motion": False,
    "consonance_treatment": "all_onsets",
    "cont_rhythms": "none",
    "vary_rhythm_consistently": False,
    "rhythmic_unison": False,
    "rhythmic_quasi_unison": False,
    "hocketing": False,
    "onset_density": (0.05, 0.05, 0.05),
    "dur_density": (0.6, 0.7, 0.5),
    "onset_subdivision": 1.0,
    "randomly_distribute_between_choirs": True,
    "length_choir_segments": -0.25,
    "tempo": 126,
}
