{
"seed": 814091092,
"num_voices": 5,
"pattern_len": (2.5, 3.5, 2.5, 6.5, 4),
"rhythm_len": (2.5, 3.5, 2.5, 6.5, 4),
"pitch_loop": 4,
"harmony_len": (7.5, 3, 6.5, 1.5, 4.5),
"truncate_patterns": False,
"voice_order_str": "usual",
"interval_cycle": (7, 7),
"chords": (1.25, 1.5, 1.875),
"parallel_voice_leading": False,
"voice_lead_chord_tones": False,
"preserve_foot_in_bass": "lowest",
"chord_tone_and_foot_disable": False,
"chord_tone_selection": True,
"force_chord_tone": "global_first_note",
"chord_tones_sync_attack_in_all_voices": False,
"force_foot_in_bass": "global_first_beat",
"prefer_small_melodic_intervals": True,
"force_repeated_notes": False,
"force_parallel_motion": True,
"consonance_treatment": "none",
"cont_rhythms": "none",
"vary_rhythm_consistently": False,
"rhythmic_unison": False,
"rhythmic_quasi_unison": False,
"hocketing": False,
"attack_density": (0.85, 0.7, 0.65, 0.65, 0.5),
"dur_density": (0.25, 0.6, 0.4, 0.7, 0.7),
"attack_subdivision": 0.3333333333333333,
"randomly_distribute_between_choirs": True,
"length_choir_segments": 1.75,
"tempo": 136,
}
