{
    "choirs": [16, 21, 15],
    # eventually I would like to migrate some of these values over to the script
    "max_interval": 4,
    "force_foot_in_bass": "global_first_beat",
    "force_chord_tone": "global_first_note",
    "pattern_len": 2,
    "harmony_len": 4,
    "foot_pcs": [0, 5, 10, 3],
    "preserve_foot_in_bass": "lowest",
    "scales": ["NATURAL_MINOR_SCALE"],
    "chords": ["MINOR_TRIAD"],
    "randomly_distribute_between_choirs": True,
    "length_choir_segments": 2,
    "max_super_pattern_len": 64,
    "max_consec_seg_from_same_choir": 1,
    "onset_density": 0.65,
    "dur_density": 0.65,
    "voice_lead_chord_tones": True,
    "tempo": 144,
    "consonance_treatment": "none",
    "consonances": [0, 3, 4, 5, 7, 8, 9],
    "num_voices": 1,
    "pattern_len": 2,
    "num_harmonies": 1,
    "harmony_len": 1,
    "num_reps_super_pattern": 1,
}
