{
    "choirs": [8, 17, 14],
    "num_harmonies": 4,
    "max_interval": 4,
    "force_foot_in_bass": "global_first_beat",
    "force_chord_tone": "global_first_note",
    "pattern_len": 2,
    "harmony_len": 4,
    "foot_pcs": [0, 5, 10, 3],
    "preserve_foot_in_bass": "lowest",
    "scales": [NATURAL_MINOR_SCALE],
    "chords": [MINOR_TRIAD],
    "parallel_voice_leading": True,
    # "parallel_direction": "down",
    "constrain_voice_leading_to_ranges": True,
}
