{
    "seed": 1987650998,
    "num_voices": 4,
    "pattern_len": 3,
    "rhythm_len": 5,
    "pitch_loop": False,
    "harmony_len": 7,
    "truncate_patterns": False,
    "voice_order_str": "usual",
    "interval_cycle": (10, 11, 4, 3, 8),
    "chords": (1.5, 1.875, 2.25),
    "parallel_voice_leading": False,
    "voice_lead_chord_tones": False,
    "preserve_foot_in_bass": "none",
    "chord_tone_and_foot_disable": False,
    "chord_tone_selection": False,
    "force_chord_tone": "first_note",
    "chord_tones_sync_onset_in_all_voices": False,
    "force_foot_in_bass": "none",
    "prefer_small_melodic_intervals": True,
    "force_repeated_notes": True,
    "force_parallel_motion": True,
    "consonance_treatment": "all_durs",
    "cont_rhythms": "none",
    "vary_rhythm_consistently": False,
    "rhythmic_unison": False,
    "rhythmic_quasi_unison": False,
    "hocketing": False,
    "onset_density": (0.6, 0.7, 0.5, 0.65),
    "dur_density": (0.9, 0.75, 0.2, 0.55),
    "onset_subdivision": 0.25,
    "randomly_distribute_between_choirs": True,
    "length_choir_segments": -0.25,
    "tempo": 129,
}
