{
    "seed": 299148060,
    "num_voices": 3,
    "pattern_len": 2,
    "rhythm_len": 2,
    "pitch_loop": False,
    "harmony_len": 7,
    "truncate_patterns": True,
    "voice_order_str": "reverse",
    "interval_cycle": 7,
    "chords": ((1.0, 1.25, 1.5), (1.33333, 1.66667, 2.0)),
    "parallel_voice_leading": False,
    "voice_lead_chord_tones": True,
    "preserve_foot_in_bass": "none",
    "chord_tone_and_foot_disable": False,
    "chord_tone_selection": True,
    "force_chord_tone": "first_beat",
    "chord_tones_sync_onset_in_all_voices": False,
    "force_foot_in_bass": "global_first_beat",
    "prefer_small_melodic_intervals": True,
    "force_repeated_notes": False,
    "force_parallel_motion": False,
    "consonance_treatment": "none",
    "cont_rhythms": "none",
    "vary_rhythm_consistently": False,
    "rhythmic_unison": False,
    "rhythmic_quasi_unison": True,
    "hocketing": False,
    "onset_density": (0.05, 0.25, 0.95),
    "dur_density": 0.4,
    "onset_subdivision": 0.25,
    "randomly_distribute_between_choirs": True,
    "length_choir_segments": 0.5,
    "tempo": 130,
}
