{
    # Generated randomly on 2021-01-15
    "seed": 631207953,
    "num_voices": 3,
    "pattern_len": (7.5, 5.5, 3.5),
    "rhythm_len": 1,
    "pitch_loop": 0,
    "harmony_len": (7.5, 5.5, 3.5),
    "truncate_patterns": False,
    "voice_order_str": "usual",
    "interval_cycle": 6,
    "chords": (
        (1.25, 1.5, 1.875),
        (1.5, 1.875, 2.25),
        (1.125, 1.35, 1.6875),
        (1.25, 1.5, 1.875),
    ),
    "parallel_voice_leading": True,
    "voice_lead_chord_tones": False,
    "preserve_foot_in_bass": "all",
    "chord_tone_and_foot_disable": False,
    "chord_tone_selection": True,
    "force_chord_tone": "first_beat",
    "chord_tones_sync_onset_in_all_voices": False,
    "force_foot_in_bass": "first_note",
    "prefer_small_melodic_intervals": True,
    "force_repeated_notes": False,
    "force_parallel_motion": False,
    "consonance_treatment": "all_durs",
    "cont_rhythms": "none",
    "vary_rhythm_consistently": False,
    "rhythmic_unison": False,
    "rhythmic_quasi_unison": False,
    "hocketing": True,
    "onset_density": (0.7, 0.95, 0.95),
    "dur_density": (0.95, 0.25, 0.3),
    "onset_subdivision": 0.25,
    "randomly_distribute_between_choirs": True,
    "length_choir_segments": 1.25,
    "tempo": 130,
    # added these bounds later:
    # "hard_bounds": [(21, 84)],
}
