# TODO create example_base.py, share it among examples
{
    "seed": 2,
    "pattern_len": 2,
    "num_harmonies": 4,
    "harmony_len": 4,
    "num_voices": 2,
    "foot_pcs": [0],
    "interval_cycle": 3,
    "attack_density": 0.7,
    "prohibit_parallels": [0],
    "forbidden_interval_classes": [0],
    "max_repeated_notes": 0,
    "force_foot_in_bass": "global_first_beat",
    "consonance_treatment": "all_attacks",
    "voice_lead_chord_tones": True,
    "hocketing": True,
    "max_interval": 4,
    "output_path": "examples/midi/example1.mid",
    "overwrite": True,
}
