{
    "seed": 2,
    "pattern_len": 2,
    "harmony_len": 2,
    "root_pcs": [0, 5, 10, 3],
    "num_reps_super_pattern": 2,
    "overlap": False,
    "consonance_treatment": "all_attacks",
    "obligatory_attacks": [0, 1],
    "obligatory_attacks_modulo": [2],
    "num_voices": 3,
    "attack_density": [0.5, 0.7],
    "dur_density": [0.5, 0.7],
    "voice_lead_chord_tones": True,
    "allow_flexible_voice_leading": False,
    # "prefer_small_melodic_intervals_coefficient": 0.2,
    # "consonances": [3, 4, 8, 9],
    "max_interval": -5,
    "preserve_root_in_bass": "lowest",
    "chord_tone_selection": True,
    "chord_tones_sync_attack_in_all_voices": True,
    "try_to_force_non_chord_tones": True,
    "voice_leading_attempts": 200,
}
