# Illustrates harmony_len shorter than pattern_len
{
    "seed": 2,
    "pattern_len": 4,
    "num_harmonies": 4,
    "harmony_len": 2,
    "num_voices": 2,
    "root_pcs": [0],
    "interval_cycle": 3,
    "attack_density": 0.7,
    "prohibit_parallels": [0],
    "forbidden_interval_classes": [0],
    "max_repeated_notes": 0,
    "obligatory_attacks": [[0], []],
    "obligatory_attacks_modulo": 2,
    "force_root_in_bass": "first_beat",
    "voice_ranges": [(51, 60), (60, 72)],
    "extend_bass_range_for_roots": 12,
    "consonance_treatment": "all_attacks",
    "voice_lead_chord_tones": True,
    "hocketing": True,
    "max_interval": 4,
    "output_path": "examples/midi/example7.mid",
    "overwrite": True,
    "num_reps_super_pattern": 8,  # TODO 4
}
