# similar to example3.py but voices have different values of rhythm_len
{
    "seed": 2,
    "pattern_len": 4,
    "rhythm_len": [1.5, 2],
    "num_harmonies": 4,
    "harmony_len": 4,
    "num_voices": 2,
    "root_pcs": [0],
    "interval_cycle": 3,
    "attack_density": [0.7, 0.85],
    "prohibit_parallels": [0],
    "forbidden_interval_classes": [0],
    "max_repeated_notes": 0,
    "force_root_in_bass": "global_first_beat",
    "consonance_treatment": "all_attacks",
    "max_interval": 4,
    "output_path": "examples/midi/example4.mid",
    "overwrite": True,
}
