{
    # "seed": 2,
    # "pattern_len": 2,
    # "harmony_len": 4,
    # "num_voices": 4,
    # "foot_pcs": ("E", "G", "C", "A"),
    # "chords": ("MAJOR_TRIAD", "MAJOR_TRIAD", "MINOR_TRIAD", "MAJOR_TRIAD"),
    # "scales": ("DIATONIC_SCALE", "MIXOLYDIAN", "AEOLIAN", "LYDIAN"),
    # "voice_ranges": "AUTHENTIC_OCTAVES * G * OCTAVE2",
    # "attack_density": 0.4,
    # "dur_density": 0.8,
    # "prohibit_parallels": [0],
    # "force_foot_in_bass": "global_first_beat",
    # "consonance_type": "chordwise",
    # "chord_permit_doublings": "complete",
    # "consonance_treatment": "all_attacks",
    # "voice_lead_chord_tones": True,
    # "max_repeated_notes": -1,
    # "max_alternations": 0,
    # "rhythmic_unison": True,
    # "output_path": "examples/midi/",
    # "overwrite": True,
    "pattern_len": 4,
    "consonance_treatment": "none",
    # "harmony_len": 4,
    "seed": 2,
    "output_path": "examples/midi/",
    "overwrite": True,
    "force_foot_in_bass": "first_beat",
    "extend_bass_range_for_foots": 7,
    "voice_lead_chord_tones": True,
    "attack_density": 0.7,
    "dur_density": 0.7,
    "unison_weighted_as": "SECOND",
    "randomly_distribute_between_choirs": True,
    "length_choir_segments": 1/4,
    "tempo": 132,
}
